### PR TITLE
Added Event Handler

### PR DESCRIPTION
**Pull request by Starystars67**
I felt this would make the resource more useful allowing developers to open and close the menu from other locations.

### CODE REVIEW

**Comment by carmineos** [comment]
I should add another config field to enable disable menu opening using the specified control and keep the event handler, so whoever wants can disable the opening by hotkey and just use the event or move the UI in another script or maybe replace NativeUI

**Comment by Starystars67** [comment]
Yeah that sounds like a good idea @neos7 However my build failed 'thats what you get for just writing it in github only i guess'. Are you able to just resolve the issue in my commit for me please?

**Comment by carmineos** [comment]
Just remove `<>` after new Action as it doesn't take any argument

**Comment by Starystars67** [comment]
Any idea how i can add that to this commit / pull request?

**Comment by carmineos** [comment]
I guess you just need to keep pushing commits to the same branch
`Add more commits by pushing to the patch-1 branch on Starystars67/fivem-vstancer.`

**Comment by Starystars67** [comment]
Haha yeah found it :P I feel sometime GitHub isn't the clearest of platforms but it works so well when you know 100% what your doing. Cheers

**Pull request closed without merging**
